### ISSUE TITLE
new namings of some channels

### ISSUE THREAD

**Issue by damnms** [mathewmeconry/TV7_EPG_Data#14]
Hi, i noticed some channels have been renamed, at least on init7.
For example arte is now "Arte D". Unfortunately, there are some of those that have been changed. I can give you a list if that helps you in any way to update that.

**Comment by mathewmeconry** [comment]
Hey @damnms 
A list would be nice so I can adjust the mapping

**Comment by damnms** [comment]
arte D
RTLZWEI (Schweiz)
Kabel Eins (Schweiz)
ONE
NITRO
SAT.1 GOLD
Servus TV
Tele Top
ShF
BR Fernsehen Süd
WDR Fernsehen
NDR FS NDS
hr Fernsehen
euronews D
meteonews.TV
Comedy Central
Lilo TV

There are more but this is the list of the german speaking channels with missing EPG information

**Comment by mathewmeconry** [comment]
Hi @damnms 
I fixed the mapping issue for the channels I found and added init7s EPG API as a source.
The files are in the process of being updated and it should be done in around 40 minutes. So when you can test that would be great. I am currently not able to test the EPG file myself.

**Comment by damnms** [comment]
Did unfortunately not work. I am wondering what has been changed?

**Comment by mathewmeconry** [comment]
Yeah I had a bug in the changes I did and it is resolved now (#15)
Can you check if the channels are now mapped better?

**Comment by damnms** [comment]
That looks very good! Even comedy central is now in the list! 
But some are still missing, e.g. "Das Erste" - i assume that was "ARD" before.

I also found a funny typo, channel id="tagessau24" :D 

when i validate the file with tv_validate_file it says:
oli@DESKTOP-RA0V02P:~/Downloads$ tv_validate_file tv7_epg.xml/tv7_epg.xml 
The file is not valid according to the xmltv dtd:
 tv7_epg.xml/tv7_epg.xml:1: validity error : Element programme content does not follow the DTD, expecting (title+ , sub-title* , desc* , credits? , date? , category* , keyword* , language? , orig-language? , length? , icon* , url* , country* , episode-num* , video? , audio? , previously-shown? , premiere? , last-chance? , new? , subtitles* , rating* , star-rating* , review*), got (icon title)
tv7_epg.xml/tv7_epg.xml:1: validity error : Element programme content does not follow the DTD, expecting (title+ , sub-title* , desc* , credits? , date? , category* , keyword* , language? , orig-language? , length? , icon* , url* , country* , episode-num* , video? , audio? , previously-shown? , premiere? , last-chance? , new? , subtitles* , rating* , star-rating* , review*), got (icon title)
...

Not sure if thats related to the missing text. Can you modify the entries so that they match the order as defined in the xmltv.dtd?

**Comment by mathewmeconry** [comment]
I added the Das Erste mapping and fixed the tagessau :P 
I also change the order in the XML to match the DTD but the `tv_validate_file` command throws now errors about invalid IDs. The reason is that xmltv expects TLDs to be present with the channel id (old remenant?). I won't fix this because I don't want to mess too much with the IDs otherwise you can get mapping issues against the playlist.

**Comment by damnms** [comment]
awesome! nearly all channels are now working.
the only ones left (german lang) are:
ONE
Servus TV
ShF
hr Fernsehen
meteonews.TV
KiKA
Lilo TV

Thanks!!

**Comment by mathewmeconry** [comment]
Unfortunately, teleboy doesn't have epg data for all the channels. Thus I added the ones from your list that were available. The updated epg files will be generated this night.
